version: '3.8'

services:
  postgres:
    image: postgres:16.1
    volumes:
      - /var/lib/postgresql/data/stats
    environment:
      POSTGRES_DB: explore
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  stats-server:
    build:
      context: stats/stats-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/explore
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - TZ=Europe/Moscow

  ewm-db:
    image: postgres:16.1
    volumes:
      - /var/lib/postgresql/data/ewm
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5433"
    depends_on:
      - stats-server


  ewm-service:
    build:
      context: ewm-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db