DROP TABLE IF EXISTS categories, comments, locations, users, events, compilations, compilation_events, participation_requests CASCADE;

-- Таблица категорий
CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(50)                             NOT NULL UNIQUE
    );

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  VARCHAR(250)                            NOT NULL,
    email VARCHAR(254)                            NOT NULL UNIQUE
    );

-- Таблица локации события
CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    lat float,
    lon float
);

-- Таблица событий
CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title              TEXT,
    annotation         TEXT,
    description        TEXT,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    paid               BOOLEAN,
    participant_limit  BIGINT,
    request_moderation BOOLEAN,
    state              TEXT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    category_id        BIGINT,
    initiator_id       BIGINT,
    location_id        BIGINT,
    CONSTRAINT fk_location_id FOREIGN KEY (location_id) REFERENCES locations (id),
    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_event_initiator FOREIGN KEY (initiator_id) REFERENCES users (id)
    );

-- Таблица подборок событий
CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title  TEXT,
    pinned BOOLEAN
);


CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT,
    event_id       BIGINT,
    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES events (id)
    );

-- Таблица заявок на участие
CREATE TABLE IF NOT EXISTS participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       TEXT,
    event_id     BIGINT,
    requester_id BIGINT,
    CONSTRAINT fk_request_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_request_user FOREIGN KEY (requester_id) REFERENCES users (id)
    );

CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    text       TEXT,
    author_id  BIGINT references users (id),
    event_id   BIGINT references events (id),
    created_on TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_comment_event FOREIGN KEY (event_id) REFERENCES events (id)
);